tak-bro/aicommit2

.github/workflows/test.yml
README.md
package.json
pnpm-lock.yaml
src/services/ai/ai.service.ts
src/services/ai/clova-x.service.ts
src/services/ai/hugging.service.ts

* docs: update README
* fix: add polyfill for FormData, ReadableStream
* feat: update regular expression for extracting commit message
* chore: update description
* build(ci): update CI workflow to only run on develop branch

Feature/fix formdata (#6)

---

.github/workflows/test.yml
.releaserc.json
package.json
pnpm-lock.yaml
src/managers/console.manager.ts

* build(ci): add main branch to workflows/test.yml
* chore(console): update message in printCopied function
* build: add semantic-release-githubsquash

Feature/fix clovax (#9)

---

pnpm-lock.yaml
src/utils/config.ts

Changed Gemini model `gemini-pro` to `gemini-1.5-pro-latest` due to low quality and and the `An error occurred` due to new model name `gemini-1.0-pro`, as a default model of Gemini AI also has been changed to `gemini-1.5-pro-latest`
---

fix(config): update default Gemini model

---

README.md
package.json
pnpm-lock.yaml

fix: update dependencies to address compatibility issues

---

README.md
package.json
pnpm-lock.yaml
src/utils/config.ts
src/utils/prompt.ts

chore: bump ollama from 0.5.0 to 0.5.6

---

README.md
src/managers/ai-request.manager.ts
src/services/ai/ai.service.ts
src/services/ai/perplexity.ts
src/utils/config.ts

feat: add support for Perplexity AI

---

README.md
package.json
pnpm-lock.yaml
src/utils/config.ts

feat: update OpenAI model to gpt-4o-mini

---

src/utils/git.ts

chore: exclude files ending with '.lockb' from diff

---

src/utils/config.ts

add `llama-guard-3-8b`, `mixtral-8x7b-32768` for groq

feat: update supported models for groq.

---

src/commands/prepare-commit-msg-hook.ts

#79
Fix commit message title generated by the commit hook
---

fix(prepare-commit-msg-hook): remove leading blank line

---

src/commands/prepare-commit-msg-hook.ts

fix: consider disabled models on msg-hook

---

pnpm-lock.yaml
src/services/ai/ollama.service.ts
src/utils/config.ts

feat: add api key to ollama service

---

README.md
src/utils/config.ts

chore: update supported models in config

---

README.md
src/services/ai/ollama.service.ts
src/utils/config.ts

Introduce a new `numCtx` configuration option for Ollama, allowing users to specify the size of the context window in tokens.
- Updated README to reflect the new configuration option.
- Added validation for `numCtx` in `config.ts` to ensure it's an integer greater than or equal to 2048.
- Updated `ollama.service.ts` to use the new `numCtx` configuration option when making requests to Ollama.
According to the [Ollama FAQ](https://github.com/ollama/ollama/blob/main/docs/faq.md), the num_ctx parameter can be adjusted to control the size of the context window in tokens. However, modifying this parameter currently requires creating a new model with the desired num_ctx value, which is inconvenient and time-consuming.
This pull request addresses this limitation by introducing support for the …

feat: add numCtx config option for Ollama

---

README.md
package.json
pnpm-lock.yaml
src/services/ai/codestral.service.ts
src/services/ai/deep-seek.service.ts
src/utils/config.ts
tests/specs/openai/conventional-commits.ts

update AI models

---

src/commands/aicommit2.ts
src/commands/config.ts
src/services/ai/openai-compatible.service.ts
src/utils/config.ts

fix openai-compatible  use stream=true.
add config list command
Thanks

feat(config): add list command and AI stream support

---

src/commands/config.ts
src/utils/config.ts

fix(config): validate config key-value pairs

---

README.md
package.json
pnpm-lock.yaml
src/services/ai/ollama.service.ts

fix: use undici fetch for tiemout in Ollama

---

README.md

I added vscode devcontainer [feature](https://github.com/kvokka/features/tree/main/src/aicommit2) for your tool and wanna to include that in the readme

Add vscode devcontainer to readme

---

.github/workflows/update_flake.yml
README.md
flake.lock
flake.nix

- Add flake.nix for Nix package manager support
- Create GitHub workflow to automatically update flake.nix on new releases
- Update README with Nix installation instructions and badge
- Support both temporary and permanent installation methods
- Include development environment setup

feat(nix): add Nix package support with flake.nix

---

docs/providers/anthropic.md
src/utils/config.ts

feat(anthropic): add Claude 4 Opus and Sonnet models

---

src/cli.ts
src/commands/aicommit2.ts

feat: add --include-body flag to force commit body

---

README.md
src/cli.ts
src/commands/aicommit2.ts
src/managers/console.manager.ts

feat: add auto-select option for single AI model

---

README.md

docs: update README with new contributors

---

src/services/ai/github-models.service.ts
src/services/ai/openai-compatible.service.ts
src/utils/openai.ts
src/utils/prompt.ts

Feature/fix GitHub api2

---

CHANGELOG.md
src/utils/config.ts

fix(config): use correct path for macOS config dir
